# slet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: mySkillet_test_edl
# label used for menu selection
label: LG_Test
description: Local Gov Test skillet
#
# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
#extends:
#
# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
  - myCollection
#
# ---------------------------------------------------------------------
# end of preamble section
#
# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
#variables:
- name: EDL_NAME
    description: External-list name
    default: my_edl
    type_hint: text
  - name: EDL_Description
    description: External-list description
    default: my_edl description
    type_hint: text
  - name: Edl_URL
    description: External-list URL
    default: my_edl
    type_hint: url
  - name: Tag_Name
    description: tag name
    default: my_tag
    type_hint: text
  - name: Tag_description
    description: tag description
    default: tag description
    type_hint: text
  - name: tag_color
      description: tag color
      default: red
      type_hint: dropdown
      dd_list:

#
# ---------------------------------------------------------------------
# end of variables section
#
# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order
#
# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: external-list-890364
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
        <external-list>
                    <entry name=" {{ EDL_NAME }} ">
                      <type>
                        <ip>
                          <recurring>
                            <five-minute/>
                          </recurring>
                          <description> {{ EDL_Description }} </description>
                          <url> {{ Edl_URL }} </url>
                        </ip>
                      </type>
                    </entry>
                  </external-list>

  - name: tag-99616
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
                    <entry name="{{ Tag_Name }}">
                      <color>{{ tag_color }}</color>
                      <comments>{{ Tag_description }}</comments>
                    </entry>

  - name: security-145052
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase
    element: |-
        <security>
                      <rules>
                        <entry name=" {{ EDL_NAME_OUT }} " uuid="d104d347-a2be-4ab3-a787-f40f8d416935">
                          <to>
                            <member>any</member>
                          </to>
                          <from>
                            <member>any</member>
                          </from>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member> {{ EDL_NAME }}</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>any</member>
                          </application>
                          <service>
                            <member>application-default</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <action>deny</action>
                          <description> {{ EDL_NAME_OUT }} </description>
                        </entry>
                        <entry name=" {{ EDL_NAME_IN }} " uuid="8551895c-8111-47fa-b3b4-53a88b897d14">
                          <to>
                            <member>any</member>
                        </to>
                          <from>
                            <member>any</member>
                          </from>
                          <source>
                            <member> {{ EDL_NAME }}</member>
                          </source>
                         <destination>
                            <member>any</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>any</member>
                          </application>
                          <service>
                            <member>application-default</member>
                          </service>
                          <hip-profiles>
                            <member>any</member>
                          </hip-profiles>
                          <action>deny</action>
                          <description> {{ EDL_NAME_IN }} </description>
                        </entry>
                      </rules>
                    </security>


# ---------------------------------------------------------------------
# end of snippets sectionkil